In [25]:
import numpy as np

#Coefficient matrix A (5x5 matrix)
A = np.array([
    [3, 2, 1, 1, 0],
    [1, 4, 2, 0, 1],
    [2, 3, 4, 1, 0],
    [1, 1, 3, 5, 0],
    [0, 1, 2, 4, 3]
])

#Constant matrix B (5x1 matrix)
B = np.array([100, 150, 120, 110, 140])

#Check if matrix A is invertible (determinant should not be zero)
det_A = np.linalg.det(A)
if det_A == 0:
    print("Matrix A is singular and cannot be inverted!")
else:
    #Find the inverse of matrix A
    A_inv = np.linalg.inv(A)

    #Solve for X using the matrix inverse method
    X = np.dot(A_inv, B)

    print("Solution (Unknowns):")
    print(X)

Solution (Unknowns):
[ 7.36462094 32.23826715 -1.62454874 15.05415162 16.93140794]


# Problem 1

In [29]:
#Define the coefficient matrix A (3x3 matrix)
A = np.array([
    [2, 1, -1],
    [-1, 3, 2],
    [1, -2, 4]
])

#Define the constant matrix B (3x1 matrix)
B = np.array([5, 6, 7])

#Check if matrix A is invertible (determinant should not be zero)
det_A = np.linalg.det(A)
if det_A == 0:
    print("Matrix A is singular and cannot be inverted!")
else:
    #Find the inverse of matrix A
    A_inv = np.linalg.inv(A)

    #Solve for X using the matrix inverse method
    X = np.dot(A_inv, B)

    print("Solution (Unknowns):")
    print(X)

Solution (Unknowns):
[2.64102564 1.61538462 1.8974359 ]


# Problem 2

In [67]:
#Define the coefficient matrix A (5x5 matrix)
A = np.array([
    [5, 3, 1, 1, 0],
    [4, 6, 2, 0, 1],
    [2, 7, 3, 1, 0],
    [1, 2, 4, 5, 0],
    [3, 4, 5, 0, 6]
])

#Define the constant matrix B (5x1 matrix)
B = np.array([200, 300, 150, 120, 250])

#Check if matrix A is invertible (determinant should not be zero)
det_A = np.linalg.det(A)

if det_A == 0:
    print("Matrix A is singular and cannot be inverted!")
else:
    #Find the inverse of matrix A
    A_inv = np.linalg.inv(A)

    #Solve for X using the matrix inverse method
    X = np.dot(A_inv, B)

    print("Solution (Unknowns):")
    print(X)

Solution (Unknowns):
[ -23.86666667  137.6        -336.          242.53333333  241.86666667]


# Problem 3

In [45]:
#Define the coefficient matrix A (7x7 matrix)
A = np.array([
    [1, 2, 3, 4, 5, 6, 7],
    [4, 6, 2, 4, 6, 2, 1],
    [7, 5, 3, 2, 4, 5, 7],
    [1, 5, 7, 4, 3, 9, 2],
    [2, 5, 6, 3, 2, 5, 8],
    [3, 2, 4, 5, 7, 1, 4],
    [3, 1, 5, 7, 3, 5, 2]
])

#Define the constant matrix B (7x1 matrix)
B = np.array([10, 20, 30, 40, 50, 60, 70])

#Check if matrix A is invertible (determinant should not be zero)
det_A = np.linalg.det(A)
if det_A == 0:
    print("Matrix A is singular and cannot be inverted!")
else:
    #Find the inverse of matrix A
    A_inv = np.linalg.inv(A)

    #Solve for X using the matrix inverse method
    X = np.dot(A_inv, B)

    print("Solution (Unknowns):")
    print(X)

Solution (Unknowns):
[ 5.04903254 -3.24742872 12.72106153  3.78185405 -1.75960383 -5.25219523
 -0.21908362]


# Problem 4

In [49]:
#Define the coefficient matrix A (5x5 matrix) with the actual values
A = np.array([
    [1, 2, 3, 4, 7],
    [6, 3, 7, 5, 3],
    [2, 4, 4, 6, 1],
    [4, 5, 7, 7, 5],
    [7, 6, 2, 8, 7]
])

#Define the constant matrix B (5x1 matrix) with the actual values
B = np.array([10, 20, 30, 40, 50])

#Check if matrix A is invertible (determinant should not be zero)
det_A = np.linalg.det(A)
if det_A == 0:
    print("Matrix A is singular and cannot be inverted!")
else:
    #Find the inverse of matrix A
    A_inv = np.linalg.inv(A)

    #Solve for X using the matrix inverse method
    X = np.dot(A_inv, B)

    print("Solution (Unknowns):")
    print(X)

Solution (Unknowns):
[-1.77635684e-15  1.50000000e+01 -8.88178420e-16 -5.00000000e+00
 -8.88178420e-16]


# Problem 5

In [65]:
def matrix_inversion(A, B):

    try:
        # Calculate the inverse of A
        A_inv = np.linalg.inv(A)
        
        # Compute the solution X = A_inv * B
        X = np.dot(A_inv, B)
        return X
    except np.linalg.LinAlgError:
        print("Matrix A is singular and cannot be inverted.")
        return None

A = np.array([
    [5, 3, 1, 1, 0],
    [4, 6, 2, 0, 1],
    [2, 7, 3, 1, 0],
    [1, 2, 4, 5, 0],
    [3, 4, 5, 0, 6]
])

B = np.array([200, 300, 150, 120, 250])

matrix_inversion(A, B)

array([ -23.86666667,  137.6       , -336.        ,  242.53333333,
        241.86666667])